version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - tabantajnetwork

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    tty: true
    volumes:
          - "./infra/postgres/data:/var/lib/postgresql/data"
    environment:
          - POSTGRES_USER=homestead
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=homestead
    ports:
          - "5432:5432"
    networks:
          - tabantajnetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - tabantajnetwork

  # nginx-amplify:
  #   image: nginx-amplify-agent
  #   container_name: nginx-amplify
  #   restart: unless-stopped
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /etc/nginx-amplify:/etc/amplify
  #   environment:
  #     - AMPLIFY_IMAGENAME=nginx
  #     - AMPLIFY_APIKEY=7cb260676b00276f4e0be01bf4cba131
  #   networks:
  #     - tabantajnetwork

networks:
  tabantajnetwork:
