version: "3.8"
services:
  nginx-tabantaj:
    image: nginx:stable-alpine
    container_name: nginx-tabantaj #uncommment if will not use swarm
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres-tabantaj
    networks:
      - tabantajnetwork
    # deploy:
    #   replicas: 1 # Set the desired number of replicas
    #   restart_policy:
    #     condition: on-failure

  postgres-tabantaj:
    image: postgres:14-alpine
    container_name: postgres-tabantaj #uncomment if will not use swarm mode
    restart: unless-stopped
    tty: true
    volumes:
      - "./infra/postgres/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=homestead
    ports:
      - "5432:5432"
    networks:
      - tabantajnetwork
    mem_limit: 6g

  php:
    #uncomment this if you will use only docker compose
    build:
      context: "./infra/php/Dockerfile"
      dockerfile: Dockerfile
    #     # target: php-production  # Specify the target build stage if applicable
    #     # args:
    #     # - BUILD_ENV=production  # Pass any necessary build arguments
    # #container_name: php-tabantaj
    #uncomment this if you will use only docker compose
    #image: johnvo95/tabantaj_php-tabantaj:latest
    container_name: php-tabantaj
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - tabantajnetwork
    # deploy:
    #   replicas: 1 # Set the desired number of replicas
    #   restart_policy:
    #     condition: on-failure

networks:
  tabantajnetwork:
