version: "3.7"
services:
  nginx-tabantaj:
    image: nginx:stable-alpine
    container_name: nginx-tabantaj
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-tabantaj
      - postgres-tabantaj
    networks:
      - tabantajnetwork

  # pgadmin-tabantaj:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin-tabantaj
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "luis.vargas@silent4business.com"
  #     PGADMIN_DEFAULT_PASSWORD: "Administrador1"
  #   depends_on:
  #     - php-tabantaj
  #     - postgres-tabantaj
  #   volumes:
  #     - ./pgadmin_data:/var/lib/pgadmin
  #   networks:
  #     - tabantajnetwork

  postgres-tabantaj:
    image: postgres:latest
    container_name: postgres-tabantaj
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: 'homestead'
      POSTGRES_USER: 'homestead'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_ROOT_PASSWORD: 'secretroot'
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    networks:
      - tabantajnetwork

  php-tabantaj:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-tabantaj
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - tabantajnetwork

networks:
  tabantajnetwork:
