global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter-tabantaj:9121']

  # prometheus-nginx-exporter
  # - job_name: redis-exporter
  #   static_configs:
  #     - targets: ['nginx-exporter-tabantaj:9113']

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter-tabantaj:9187"]

  - job_name: node-exporter-tabantaj  # Add Node Exporter service
    static_configs:
      - targets: ['node-exporter-tabantaj:9100']
