name: Docker Compose build and test
run-name: ${{ github.actor }} run Docker Compose Build and Test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - fix/*
      - refactor/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        cp .env.example .env
        docker compose up -d --build
