name: Run Login Tests via Pytest
run-name: ${{ github.actor }} run Login Tests via Pytest
on:
  push:
    branches:
      - develop
      - stagging
  pull_request:
    branches:
      - develop
      - feature/*
      - hotfix/*
      - release/*
      - fix/*
      - refactor/*
      - testing/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install coverage
        run: pip install coverage

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py311 .
        continue-on-error: true


      - name: Navigate back to root directory
        run: cd ..


      - name: Test Login with pytest
        run: |
          coverage run -m pytest -v -s tests/login/login_successfully.py

      - name: Generate Coverage Report
        run: coverage report -m


